
/*

 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package populate;

import com.toedter.calendar.JDateChooser;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.LayoutManager;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.ScrollPaneLayout;
import javax.swing.event.MouseInputListener;
import static populate.Populate.connection;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Aniiket
 */
public class Hw3 extends javax.swing.JFrame {

    JCheckBox jCheckBox[], jCheckBoxSubCategory[];
    JPanel jpanelalpha;
    String[] subCatSelected;
    private int count = 0;
    String main_categories[] = {"Active Life", "Arts & Entertainment", "Automotive", "Car Rental", "Cafes", "Beauty & Spas", "Convenience Stores", "Dentists", "Doctors", "Drugstores", "Department Stores", "Education", "Event Planning & Services", "Flowers & Gifts", "Food", "Health & Medical", "Home Services", "Home & Garden", "Hospitals", "Hotels & Travel", "Hardware Stores", "Grocery", "Medical Centers", "Nurseries & Gardening", "Nightlife", "Restaurants", "Shopping", "Transportation"};
    int selectedIndex;

    /**
     * Creates new form Hw3
     */
    public Hw3() {
        initComponents();
        moreInitialization();
    }

    public void moreInitialization() {

        jButton1.addActionListener((ActionEvent e) -> {
            try {
                callButton();//To change body of generated methods, choose Tools | Templates.
            } catch (SQLException ex) {
                Logger.getLogger(Hw3.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
        JPanel jpanelnew = new JPanel();
        jpanelnew.setLayout(new GridLayout(0, 1));
        jCheckBox = new JCheckBox[main_categories.length];

        for (int i = 0; i < main_categories.length; i++) {
            jCheckBox[i] = new JCheckBox(main_categories[i]);
            jpanelnew.add(jCheckBox[i]);
        }
        jpanelnew.revalidate();
        //jScroll.setLayout(new ScrollPaneLayout());
        jScrollPane2.setMaximumSize(new Dimension(170, 194));
        jScrollPane2.setViewportView(jpanelnew);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();

        jScrollPane2 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        label2 = new java.awt.Label();

        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jLabel14 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jTextField5 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jComboBox6 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jComboBox10 = new javax.swing.JComboBox<>();
        jComboBox11 = new javax.swing.JComboBox<>();
        jComboBox12 = new javax.swing.JComboBox<>();
        jComboBox13 = new javax.swing.JComboBox<>();
        jTextField7 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("EXECUTE QUERY");

        jTabbedPane1.setBackground(new java.awt.Color(102, 0, 102));
        jTabbedPane1.setBorder(new javax.swing.border.MatteBorder(null));
        jTabbedPane1.setForeground(new java.awt.Color(255, 51, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 201, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 168, Short.MAX_VALUE)
        );
        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 201, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 168, Short.MAX_VALUE)
        );

        jScrollPane2.setViewportView(jPanel3);
        jScrollPane1.setViewportView(jPanel4);

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setText("Main Category");

        label3.setText("Review");

        label4.setText("Check In");

        jLabel9.setText("from:");

        jLabel10.setText("to:");

        jLabel11.setText("Number of Checkins");

        jLabel12.setText("Value:");

        jLabel13.setText("from:");

        jDateChooser2.setDateFormatString("MM/dd/yyyy");

        jLabel14.setText("to:");

        jDateChooser3.setDateFormatString("MM/dd/yyyy");

        jLabel15.setText("Stars:");

        jLabel16.setText("Value:");

        jLabel17.setText("Votes");

        jLabel18.setText("Value:");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"= , > , <", "=", ">", "<"}));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"= , > , <", "=", ">", "<"}));
        jToggleButton1.setText("Sub Category");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel15)
                                                        .addComponent(jLabel16))
                                                .addGap(22, 22, 22)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField5, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                                                        .addComponent(jComboBox7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel17)
                                                        .addComponent(jLabel18))
                                                .addGap(22, 22, 22)
                                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jTextField6)
                                                        .addComponent(jComboBox8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel15)
                                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(13, 13, 13)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel17)
                                        .addComponent(jComboBox8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel18)
                                        .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Day", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"}));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Hours", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"}));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Day", "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"}));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"Hours", "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23"}));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"= , > , <", "=", ">", "<"}));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
                jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 35, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(87, 87, 87)
                                .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(97, 97, 97))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(57, 57, 57)
                                                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jToggleButton1)
                                                .addGap(65, 65, 65)
                                        )
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel9)
                                                        .addComponent(jLabel11)
                                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jLabel10)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                                                        .addComponent(jLabel12)
                                                                        .addGap(18, 18, 18)
                                                                        .addComponent(jTextField1))
                                                                .addGroup(jPanel1Layout.createSequentialGroup()
                                                                        .addGap(10, 10, 10)
                                                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(10, 10, 10)
                                                                .addComponent(jComboBox9, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jLabel13)
                                                                                .addGap(80, 80, 80)
                                                                                .addComponent(jLabel14)))
                                                                .addGap(0, 18, Short.MAX_VALUE))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                                .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addContainerGap())))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(201, 201, 201))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jToggleButton1)
                                )
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                                        .addComponent(jScrollPane2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(label4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(5, 5, 5)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jLabel9)
                                                                        .addComponent(jLabel13)
                                                                        .addComponent(jLabel14))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGap(4, 4, 4))))
                                        .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(2, 2, 2)
                                                                .addComponent(jLabel10))
                                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                                .addGap(14, 14, 14)
                                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                        .addComponent(jComboBox5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                .addGap(23, 23, 23)
                                                .addComponent(jLabel11)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jComboBox9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(14, 14, 14)
                                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel12))
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(71, 71, 71)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );

        jTabbedPane1.addTab("Business", jPanel1);

        jLabel1.setText("Member Since:");

        jDateChooser1.setDateFormatString("MM/yyyy");

        jLabel2.setText("Review Count:");

        jLabel3.setText("Number of Friends:");

        jLabel4.setText("Average Stars:");

        jLabel5.setText("Select:");

        jLabel6.setText("Values:");

        jLabel7.setText("Values:");

        jLabel8.setText("Values:");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Query will appear here");
        jScrollPane3.setViewportView(jTextArea1);

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"= , > , <", "=", ">", "<"}));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"= , > , <", "=", ">", "<"}));

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"= , > , <", "=", ">", "<"}));

        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"None", "AND", "OR"}));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jScrollPane3)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(jLabel3)
                                                        .addComponent(jLabel4)
                                                        .addComponent(jLabel5))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jComboBox13, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(jComboBox10, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jComboBox12, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(jComboBox11, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(jLabel7)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(jLabel8)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                                                .addComponent(jLabel6)
                                                                                .addGap(18, 18, 18)
                                                                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addGap(93, 93, 93)))
                                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel2)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jComboBox10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(jLabel6)))
                                                .addGap(7, 7, 7)
                                                .addComponent(jLabel3)
                                                .addGap(6, 6, 6))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel7)
                                                .addComponent(jComboBox12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel4))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(jLabel8)
                                                .addComponent(jComboBox11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(jComboBox13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(138, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("User", jPanel2);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null},
                    {null, null, null, null}
                },
                new String[]{
                    "Title 1", "Title 2", "Title 3", "Title 4"
                }
        ));
        jTable1.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                onMouseClicked(e);

            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });
        jScrollPane4.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(253, 253, 253)
                                                .addComponent(jButton1))
                                        .addGroup(layout.createSequentialGroup()
                                                .addContainerGap()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                        .addComponent(jScrollPane4)
                                                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private Connection connect_to_the_DB() {
        String host = "localhost";
        String dbName = "YelpDbJson";
        int port = 1521;
        String oracle_URL = "jdbc:oracle:thin:@" + host + ":"
                + port + ":" + dbName;
        String user_name = "SYSTEM";
        String password = "tiger";
        Connection connection = null;
        try {
            Class.forName("oracle.jdbc.driver.OracleDriver");
            // Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException cnfe) {
            System.out.println("Classes not found: " + cnfe);
        }
        try {
            connection = DriverManager.getConnection(oracle_URL, user_name,
                    password);
            System.out.println("Connection successful!");
        } catch (SQLException sqle) {
            System.out.println("Connection error! Please check the username "
                    + "or password or the oracle URL that is passed" + sqle);
        }
        return connection;
    }

    public void onMouseClicked(MouseEvent e) {
        if (selectedIndex == 1) {
            //user query
            int row = jTable1.rowAtPoint(e.getPoint());
            String user_name = jTable1.getValueAt(row, 0).toString();
            System.out.println(user_name);
            if (row > 0) {

                try {
                    JFrame frame = new JFrame("User entered reviews: ");
                    frame.setLayout(new BorderLayout());
                    frame.setSize(1500, 1500);
                    frame.setLocation(25, 25);
                    frame.setVisible(true);
                    frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
                    frame.revalidate();
                    frame.repaint();

                    JTable jTable2 = new JTable();
                    jTable2.setModel(new javax.swing.table.DefaultTableModel(
                            new Object[][]{
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null},
                                {null, null, null, null}
                            },
                            new String[]{
                                "Title 1", "Title 2", "Title 3", "Title 4"
                            }
                    ));
                    JScrollPane jScrollPane10 = new JScrollPane();
                    frame.add(jScrollPane10);
                    jScrollPane10.setViewportView(jTable2);

                    Connection connection = connect_to_the_DB();

                    Statement statement = connection.createStatement();

                    String query = "select dbms_lob.substr(r.text,dbms_lob.getlength(r.text),1),"
                            + "U.USER_ID from review R, yelp_User U where u.user_id=r.user_id and U.USER_NAME='" 
                            + user_name + "'";
                    ResultSet resultSet = statement.executeQuery(query);

                    jTable2.setModel(DbUtils.resultSetToTableModel(resultSet));
                } catch (SQLException ex) {
                    Logger.getLogger(Hw3.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

        }
    }

    private void callButton() throws SQLException {
        Connection connection = connect_to_the_DB();
        selectedIndex = jTabbedPane1.getSelectedIndex();
        if (selectedIndex == 0) {
            if (jComboBox1.getSelectedIndex() != 0
                    && jComboBox2.getSelectedIndex() != 0
                    && jComboBox5.getSelectedIndex() != 0
                    && jComboBox6.getSelectedIndex() != 0
                    && jComboBox7.getSelectedIndex() != 0
                    && jComboBox8.getSelectedIndex() != 0
                    && jComboBox9.getSelectedIndex() != 0) {
                String from_day = jComboBox1.getSelectedItem().toString();
                int day;
                if (from_day.equalsIgnoreCase("Sunday")) {
                    day = 0;
                } else if (from_day.equalsIgnoreCase("Monday")) {
                    day = 1;
                } else if (from_day.equalsIgnoreCase("Tuesday")) {
                    day = 2;
                } else if (from_day.equalsIgnoreCase("Wednesday")) {
                    day = 3;
                } else if (from_day.equalsIgnoreCase("Thursday")) {
                    day = 4;
                } else if (from_day.equalsIgnoreCase("Friday")) {
                    day = 5;
                } else {
                    day = 6;
                }
                int from_hours = Integer.parseInt(jComboBox2.getSelectedItem().toString());
                String to_day = jComboBox5.getSelectedItem().toString();
                int tday;
                if (to_day.equalsIgnoreCase("Sunday")) {
                    tday = 0;
                } else if (to_day.equalsIgnoreCase("Monday")) {
                    tday = 1;
                } else if (to_day.equalsIgnoreCase("Tuesday")) {
                    tday = 2;
                } else if (to_day.equalsIgnoreCase("Wednesday")) {
                    tday = 3;
                } else if (to_day.equalsIgnoreCase("Thursday")) {
                    tday = 4;
                } else if (to_day.equalsIgnoreCase("Friday")) {
                    tday = 5;
                } else {
                    tday = 6;
                }
                int to_hours = Integer.parseInt(jComboBox6.getSelectedItem().toString());
                String select_checkin = jComboBox9.getSelectedItem().toString();
                int compare_checkin = Integer.parseInt(jTextField1.getText());
                DateFormat format = new SimpleDateFormat("dd-MMM-yy");
                String from_review_date = format.format(jDateChooser2.getDate());
                System.out.println(from_review_date);
                String to_review_date = format.format(jDateChooser3.getDate());
                String select_stars = jComboBox7.getSelectedItem().toString();
                int compare_stars = Integer.parseInt(jTextField5.getText());
                String select_votes = jComboBox8.getSelectedItem().toString();
                int compare_votes = Integer.parseInt(jTextField6.getText());
                see_selected_subCategories();
                String sel_sub = "";
                for (int i = 1; i < subCatSelected.length; i++) {
                    if (subCatSelected[i] != null) {
                        sel_sub += " " + "s.sub_category='" + subCatSelected[i] + "' or";
                    }
                }
                sel_sub = sel_sub.substring(0, sel_sub.length() - 2);
                String query = "Select distinct b.business_name,b.city,b.state,b.no_of_stars from business b, business_sub_category s,"
                        + "check_in_information c, review r where b.business_id=s.business_id and b.business_id=c.business_id "
                        + " " + "and b.business_id=r.business_id and (" + sel_sub + ") and (r.date_of_review between "
                        + "TO_DATE ('" + from_review_date + "','DD-MON-YY') AND TO_DATE('" + to_review_date + "',"
                        + "'DD-MON-YY')) and (r.stars" + select_stars + compare_stars + ") and (r.votes_total" + select_votes
                        + compare_votes + ")and (c.fromhour=" + from_hours + ") and (c.tohour=" + to_hours + ") and ( c.dayof between " + day + " and " + tday + ") and"
                        + "(c.checkincount" + select_checkin + compare_checkin + ")";

                jTextArea1.setText(query);
                jTextArea1.setLineWrap(true);
                output(connection, query);
                connection.close();

            } else {
                showMessageDialog(null, "Select all values पांडू");
            }

//           System.out.println(compare_checkin);
        } else if (selectedIndex == 1) {
            // System.out.println(jComboBox13.getSelectedIndex());

//                System.out.println("Month is: " + month + "\n" + " Year is: " + year);
            if (jComboBox13.getSelectedIndex() == 1) {
                DateFormat format = new SimpleDateFormat("MM/yyyy");
                String date = format.format(jDateChooser1.getDate());
                int month, year;
                month = Integer.parseInt(date.substring(0, 2));
                year = Integer.parseInt(date.substring(3, 7));
                String reviewCount_Selection = (String) jComboBox10.getSelectedItem();
                int value_reviewCount = Integer.parseInt(jTextField4.getText().toString());
//                System.out.println(reviewCount_Selection);
                String number_of_friends_Selection = (String) jComboBox12.getSelectedItem();
                int value_numberOfFriends = Integer.parseInt(jTextField7.getText().toString());
                String avg_stars = (String) jComboBox11.getSelectedItem();
                double value_avgStars = Integer.parseInt(jTextField3.getText().toString());
                String query = "Select U.user_name,U.YELPING_SINCE_MONTh,U.YELPING_SINCE_YEAR,U.AVG_STARS"
                        + " from yelp_user U, friends_of_user F where U.user_id=F.user_id AND U.yelping_since_year=" + year
                        + " AND U.yelping_since_month=" + month + " " + "AND U.review_count" + " " + reviewCount_Selection + " " + value_reviewCount
                        + " " + " AND U.avg_stars " + " " + avg_stars + " " + value_avgStars + " " + " AND F.no_of_friends" + " " + number_of_friends_Selection + " "
                        + value_numberOfFriends;
                jTextArea1.setText(query);
                jTextArea1.setLineWrap(true);
                output(connection, query);
                connection.close();
            } else if (jComboBox13.getSelectedIndex() == 2) {
                DateFormat format = new SimpleDateFormat("MM/yyyy");
                String date = format.format(jDateChooser1.getDate());
                int month, year;
                month = Integer.parseInt(date.substring(0, 2));
                year = Integer.parseInt(date.substring(3, 7));
                String reviewCount_Selection = (String) jComboBox10.getSelectedItem();
                int value_reviewCount = Integer.parseInt(jTextField4.getText().toString());
//                System.out.println(reviewCount_Selection);
                String number_of_friends_Selection = (String) jComboBox12.getSelectedItem();
                int value_numberOfFriends = Integer.parseInt(jTextField7.getText().toString());
                String avg_stars = (String) jComboBox11.getSelectedItem();
                double value_avgStars = Integer.parseInt(jTextField3.getText().toString());
                String query = " Select U.user_name,U.YELPING_SINCE_MONTh,U.YELPING_SINCE_YEAR,U.AVG_STARS"
                        + " from yelp_user U, friends_of_user F where U.user_id=F.user_id AND U.yelping_since_year=" + year
                        + " AND U.yelping_since_month=" + month + "" + "UNION Select U.user_name,U.YELPING_SINCE_MONTh,U.YELPING_SINCE_YEAR,U.AVG_STARS"
                        + " from yelp_user U, friends_of_user F where U.user_id=F.user_id AND U.review_count" + " "
                        + reviewCount_Selection + " " + value_reviewCount
                        + "" + "UNION Select U.user_name,U.YELPING_SINCE_MONTh,U.YELPING_SINCE_YEAR,U.AVG_STARS"
                        + " from yelp_user U, friends_of_user F where U.user_id=F.user_id AND U.avg_stars " + " "
                        + avg_stars + " " + value_avgStars
                        + " " + "UNION Select U.user_name,U.YELPING_SINCE_MONTh,U.YELPING_SINCE_YEAR,U.AVG_STARS"
                        + " from yelp_user U, friends_of_user F where U.user_id=F.user_id AND F.no_of_friends" + " " + number_of_friends_Selection + " "
                        + value_numberOfFriends;
                jTextArea1.setText(query);
                jTextArea1.setLineWrap(true);
                output(connection, query);
                connection.close();

            } else {
                showMessageDialog(null, "Well choose atleast one!");
            }

//                output(connection, query);
//                connection.close();
        }
    }

    public void see_selected_subCategories() {
        for (int i = 1; i < subCatSelected.length; i++) {
            if (jCheckBoxSubCategory[i].isSelected()) {
                subCatSelected[i] = jCheckBoxSubCategory[i].getText();
                //count++;
//                        System.out.println(subCatSelected[i]);
            }
        }

    }

    public void output(Connection connection, String query) throws SQLException {
        Statement statement;
        ResultSet resultSet;
        statement = connection.createStatement();
        resultSet = statement.executeQuery(query);
        System.out.println(resultSet);
        jTable1.setModel(DbUtils.resultSetToTableModel(resultSet));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hw3.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hw3.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hw3.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hw3.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Hw3().setVisible(true);
        });

    }

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
        String[] categories_selected = new String[28];
        int no_of_categories_selected = 0;
        for (int i = 0; i < jCheckBox.length; i++) {
            if (jCheckBox[i].isSelected()) {
                categories_selected[no_of_categories_selected] = jCheckBox[i].getText();
                no_of_categories_selected++;
            }
        }
        int count_of_categories = 0;
        for (int i = 0; i < 28; i++) {
            if (categories_selected[i] != null) {
                count_of_categories++;

            }
        }
        System.out.println(count_of_categories);
//        String []copy_of_categories_selected=new String[categories_selected.length];

        String createSubCatQuery = "select distinct bs.sub_category from business_sub_category bs, business b, business_category bc where b.business_id=bs.business_id"
                + " and b.business_id=bc.business_id and(";
        for (int i = 0; i < count_of_categories; i++) {
            if (categories_selected[i] != null) {
                createSubCatQuery += " bc.category_name = '" + categories_selected[i] + "' OR";
            }
        }
        createSubCatQuery = createSubCatQuery.substring(0, createSubCatQuery.length() - 3);

        createSubCatQuery = createSubCatQuery + ")order by bs.sub_category";
        System.out.println(createSubCatQuery);
        Connection con = null;
        jpanelalpha = new JPanel();

        jpanelalpha.setLayout(new GridLayout(0, 1));
        try {
            con = connect_to_the_DB();
            try (Statement st = con.createStatement()) {
                int count = 1;
                try (ResultSet rs = st.executeQuery(createSubCatQuery)) {
                    jCheckBoxSubCategory = new JCheckBox[500];
                    while (rs.next()) {
                        jCheckBoxSubCategory[count] = new JCheckBox(rs.getString("sub_category"));
//                        //jCheckBoxSubCategory[count].setBounds(20, 20 * count, 100 * count, 500);
                        jpanelalpha.add(jCheckBoxSubCategory[count]);
//                        System.out.println(rs.getString("sub_category"));
                        count++;
                    }
                    subCatSelected = new String[count - 1];
                    subCategoriesCount(count);
                    jpanelalpha.revalidate();
                    jScrollPane1.setMaximumSize(new Dimension(170, 194));
                    jScrollPane1.setViewportView(jpanelalpha);

                }
            }
            con.close();
        } catch (SQLException e) {
            System.out.println(e);
        }

    }

    public void subCategoriesCount(int count) {
        // this.jCheckBoxSubCategory = jCheckBoxSubCategory;
        this.count = count;
        return;
    }
    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;

    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JToggleButton jToggleButton1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    // End of variables declaration                   
}
