
SELECT DISTINCT C.USERID FROM CHECK_IN_BUSINESS C, YELPUSER Y WHERE Y.USERID=C.USERID AND Y.BIRTHPLACE='CA'
INTERSECT
SELECT DISTINCT  C.USERID FROM BUSINESS B, CHECK_IN_BUSINESS C WHERE C.BID=B.BID AND B.STATE!='CA'
MINUS 
SELECT DISTINCT C.USERID FROM BUSINESS B, CHECK_IN_BUSINESS C WHERE C.BID=B.BID AND B.STATE='CA';
