SELECT DISTINCT Y.USERID
FROM YELPUSER Y 
MINUS
SELECT DISTINCT Y.USERID 
FROM YELPUSER Y, REVIEW_ID R
WHERE Y.USERID=R.AUTHORID
INTERSECT
SELECT R.LIST_OF_COMMENTS
FROM REVIEW_LIST_OF_COMMENTS R, YELPUSER Y
WHERE (R.LIST_OF_COMMENTS=Y.USERID)
intersect
select list_of_comments
from REVIEW_LIST_OF_COMMENTS
group by list_of_comments
having count(*)>1;